<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JMeterLog" nsURI="http://www.uniandes.edu.co/jmeterlog" nsPrefix="JMeterLog">
  <eClassifiers xsi:type="ecore:EClass" name="Registro">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementos" upperBound="-1"
        eType="#//Elemento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EsEncabezado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EsTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Posicion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reporte">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TipoReporte" eType="#//TipoReporte"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archivos" lowerBound="1"
        upperBound="-1" eType="#//Archivo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TipoDeDato" eType="#//TipoDeDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Posicion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archivo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registros" upperBound="-1"
        eType="#//Registro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Arquitectura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoReporte">
    <eLiterals name="Aggregate"/>
    <eLiterals name="ResponseLatency" value="1"/>
    <eLiterals name="ResponseCodes" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDeDato">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="Numeric" value="2"/>
  </eClassifiers>
</ecore:EPackage>
